version: '3.9'

services:
  db:
    container_name: go-simplebank
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    ports:
      - 4444:5432

